
exports.GET_TASKS = "GET_TASKS";
exports.GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
exports.GET_TASKS_ERROR = "GET_TASKS_ERROR";

exports.ADD_TASK = "ADD_TASK";
exports.ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
exports.ADD_TASK_ERROR = "ADD_TASK_ERROR";

exports.UPDATE_TASK = "UPDATE_TASK";
exports.UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
exports.UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR";



