// Task Actions Types
exports.GET_TASKS = "GET_TASKS";
exports.GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
exports.GET_TASKS_ERROR = "GET_TASKS_ERROR";

exports.ADD_TASK = "ADD_TASK";
exports.ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
exports.ADD_TASK_ERROR = "ADD_TASK_ERROR";

exports.UPDATE_TASK = "UPDATE_TASK";
exports.UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
exports.UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR";


// Auth Actions Types
exports.REGISTER = 'REGISTER';
exports.REGISTER_SUCCESS = 'REGISTER_SUCCESS';
exports.REGISTER_ERROR = 'REGISTER_ERROR';

exports.LOGIN = 'LOGIN';
exports.LOGIN_SUCCESS = 'LOGIN_SUCCESS';
exports.LOGIN_ERROR = 'LOGIN_ERROR';

exports.AUTH = 'AUTH';
exports.AUTH_SUCCESS = 'AUTH_SUCCESS';
exports.AUTH_ERROR = 'AUTH_ERROR';

exports.LOGOUT = 'LOGOUT';
exports.LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
exports.LOGOUT_ERROR = 'LOGOUT_ERROR';
